### ISSUE TITLE
URL that contains DID makes 500 error

### ISSUE THREAD

**Issue by kawarimidoll** [ianklatzco/psky.app#1]
Hi, thank you for nice project.

I found that psky.app returns 500 error when URL has user's DID.

example: 

this works:
https://staging.bsky.app/profile/kawarimidoll.bsky.social/post/3juagfzruqs2u → https://psky.app/profile/kawarimidoll.bsky.social/post/3juagfzruqs2u

but this returns error: 
https://staging.bsky.app/profile/did:plc:okalufxun5rpqzdrwf5bpu3d/post/3juagfzruqs2u → https://psky.app/profile/did:plc:okalufxun5rpqzdrwf5bpu3d/post/3juagfzruqs2u

**Comment by ianklatzco** [comment]
Thank you so much for filing an issue! Please forgive me for writing broken code.

I've fixed the issue by updating [my library](https://github.com/ianklatzco/atprototools) with a new `getPosts` endpoint, which should make it slightly faster too ^^

**Comment by kawarimidoll** [comment]
Thank you! It fixed 👍 
Nice work!

**Comment by ianklatzco** [comment]
By the way, there's a discord server for developers here: https://discord.gg/TPhXBYqN
