### ISSUE TITLE
"bsky implemented embeds" ok but sometimes they fail though; please turn back on?

### ISSUE THREAD

**Issue by cooljeanius** [ianklatzco/psky.app#15]
The README says: "RETIRED bsky implemented embeds, so this code is no longer running!"
However, BlueSky's link previews often fail to render properly for me in Discord. Please turn this back on so we can have a backup method of linking to skeets for cases when the default link previewer fails?

**Comment by ianklatzco** [comment]
my friend @goeo- made https://cbsky.app/, which i think is currently running! give that a try ^^
