### ISSUE TITLE
quote skeets?

### ISSUE THREAD

**Issue by steveklabnik** [ianklatzco/psky.app#4]
Hey there!

First of all, thank you for making this! I've been really wanting it to exist. And the domain is perfect.

I've got a feature request, maybe: I use https://github.com/FixTweet/FixTweet to do similar things on twitter, but part of what makes it so good is that it shows quotes well.

Consider this skeet: https://psky.app/profile/did:plc:3danwc67lo7obz2fmdg6jxcr/post/3jup6ppmuef2g

The embed shows up in discord like this:

<img width="401" alt="image" src="https://user-images.githubusercontent.com/27786/235544844-32be19a9-7416-4a34-95a9-4e6ca41fe285.png">

but this leaves out the crucial context, that I'm quoting something.

The same thing, but fxtwitter: https://fxtwitter.com/austin_walker/status/1652101865855647745

<img width="400" alt="image" src="https://user-images.githubusercontent.com/27786/235545057-d31bf241-28dc-4b06-9c1d-7e5735d9eec1.png">

... this embedded shows the quote as well, making it more coherent

Anywho, feel free to close if you're not interested in this, but I think it would make this tool even better. Thanks!

**Comment by ianklatzco** [comment]
omg what a polite request.....

**Comment by ianklatzco** [comment]
done in [e60cb2d](https://github.com/ianklatzco/psky.app/commit/e60cb2dca798282463817075fcaa9690320de11c) !

**Comment by steveklabnik** [comment]
> omg what a polite request.....

haha thank you. I have been on the other side of this interaction many times, and so I try and be the sort of issue filer I wish I had on my own repos :)

Thanks again!
