### ISSUE TITLE
discord cutting off some link previews to 24 characters

### ISSUE THREAD

**Issue by thenorili** [ianklatzco/psky.app#8]
when the following link is shared in discord:

https://psky.app/profile/meo.bsky.social/post/3jvurz3ksmv2j

it's trimmed to an exceptionally short length as shown below.

![image](https://github.com/ianklatzco/psky.app/assets/50680474/57912077-f415-4c56-970d-c25afe1be65b)

It is a longer post. I don't find that it cuts off all previews to this short length.

Another post here works like normal and shares the whole post, the desired behavior

![image](https://github.com/ianklatzco/psky.app/assets/50680474/894b1e97-d27d-4ba4-b0b9-1ec6d10f3937)

**Comment by ianklatzco** [comment]
fix'd ^^

**Comment by ianklatzco** [comment]
(thanks so much for the high quality bug report ^^)
